/* ============================================================
   TUNDRA TEMPLATES — hand-written starter code.
   No AI involved: just clean HTML/JS you can edit like any project.
   ============================================================ */
(function () {
  'use strict';

  var EMPTY = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<!-- TUNDRA_META {"title":"My Game","blurb":"A short store blurb (max 160 chars).","desc":"Store description.","tags":["Indie","Arcade"],"age":"E","price":0,"palette":["#1B1F23","#4FB3E8"],"hint":"describe your controls here"} -->',
    '<title>My Game</title>',
    '<style>',
    '  html, body { margin: 0; height: 100%; background: #0a0d10; color: #F5FAFF;',
    '               font-family: system-ui, sans-serif; display: grid; place-items: center; }',
    '</style>',
    '</head>',
    '<body>',
    '',
    '<!-- your game here -->',
    '<h1>My Game</h1>',
    '',
    '</body>',
    '</html>'
  ].join('\n');

  var ARCADE = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<!-- TUNDRA_META {"title":"Starfall Catch","blurb":"Catch falling stars, dodge the dark shards, and chase your best score.","desc":"Starfall Catch is a tiny arcade game: guide the aurora orb, collect every star, and never touch a shard. Built as a clean single-file HTML5 starter in Tundra Studio — read the code, change the rules, make it yours.","tags":["Arcade","Catch","Cozy","Indie"],"age":"E","price":0,"palette":["#123a55","#8fd8ff"],"hint":"Arrows / A D or drag to move"} -->',
    '<title>Starfall Catch</title>',
    '<style>',
    '  html, body { margin: 0; height: 100%; background: #0a0d10; display: grid; place-items: center;',
    '    overflow: hidden; -webkit-tap-highlight-color: transparent; font-family: system-ui, sans-serif; }',
    '  canvas { width: 100%; height: auto; max-height: 100vh; aspect-ratio: 800 / 450; cursor: pointer; touch-action: none; }',
    '</style>',
    '</head>',
    '<body>',
    '<canvas id="cv"></canvas>',
    '<script>',
    '/* =========================================================',
    '   STARFALL CATCH — a Tundra Studio starter game.',
    '   Everything is plain code: read it, change it, break it.',
    '   Sections: setup -> juice -> screens -> game -> input -> loop',
    '   ========================================================= */',
    '',
    '// ---------- setup ----------',
    'var cv = document.getElementById("cv"), ctx = cv.getContext("2d");',
    'var W = 800, H = 450;                    // logical size (letterboxed by CSS)',
    'cv.width = W; cv.height = H;',
    '',
    'var C = { bg1: "#123a55", bg2: "#071b2c", star: "#ffe27a", shard: "#8d87a8",',
    '          player: "#eaf8ff", font: "#F5FAFF", accent: "#8fd8ff" };  // colors',
    '',
    'var state = "title";                      // title | play | over',
    'var score = 0, best = 0, lives = 3, t = 0;',
    'var px = W / 2, items = [], parts = [], spawnT = 0, shake = 0, flash = 0;',
    'var keys = {}, ptr = { x: W / 2, down: false, tap: false };',
    'var muted = false, AC = null;',
    '',
    'try { best = +localStorage.getItem("starfall_best") || 0; } catch (e) {}',
    '',
    '// ---------- juice (tiny helpers) ----------',
    'function beep(f, dur, type, vol) {',
    '  if (muted) return;',
    '  try {',
    '    if (!AC) AC = new (window.AudioContext || window.webkitAudioContext)();',
    '    if (AC.state === "suspended") AC.resume();',
    '    var o = AC.createOscillator(), g = AC.createGain();',
    '    o.type = type || "square"; o.frequency.value = f;',
    '    g.gain.value = vol || 0.04;',
    '    g.gain.exponentialRampToValueAtTime(0.0001, AC.currentTime + (dur || 0.08));',
    '    o.connect(g); g.connect(AC.destination); o.start(); o.stop(AC.currentTime + (dur || 0.08) + 0.02);',
    '  } catch (e) {}',
    '}',
    'function burst(x, y, color, n) {',
    '  for (var i = 0; i < (n || 12); i++) {',
    '    var a = Math.random() * 6.283, sp = 60 + Math.random() * 200;',
    '    parts.push({ x: x, y: y, vx: Math.cos(a) * sp, vy: Math.sin(a) * sp,',
    '                 t: 0.5, c: color, s: 2 + Math.random() * 3 });',
    '  }',
    '}',
    '',
    '// ---------- screens ----------',
    'function drawTitle() {',
    '  ctx.textAlign = "center";',
    '  ctx.fillStyle = C.font; ctx.font = "800 52px system-ui, sans-serif";',
    '  ctx.fillText("Starfall Catch", W / 2, H / 2 - 40);',
    '  ctx.fillStyle = C.accent; ctx.font = "700 16px system-ui, sans-serif";',
    '  ctx.fillText("catch the stars \\u00b7 dodge the shards", W / 2, H / 2 + 4);',
    '  ctx.globalAlpha = 0.5 + 0.5 * Math.sin(t * 4);',
    '  ctx.fillStyle = C.font; ctx.font = "600 17px system-ui, sans-serif";',
    '  ctx.fillText("PRESS SPACE OR TAP TO START", W / 2, H / 2 + 56);',
    '  ctx.globalAlpha = 1; ctx.textAlign = "left";',
    '}',
    'function drawOver() {',
    '  ctx.fillStyle = "rgba(5,8,12,0.62)"; ctx.fillRect(0, 0, W, H);',
    '  ctx.textAlign = "center";',
    '  ctx.fillStyle = C.accent; ctx.font = "800 44px system-ui, sans-serif";',
    '  ctx.fillText("GAME OVER", W / 2, H / 2 - 40);',
    '  ctx.fillStyle = C.font; ctx.font = "700 22px system-ui, sans-serif";',
    '  ctx.fillText("SCORE  " + score, W / 2, H / 2 + 6);',
    '  ctx.font = "600 15px system-ui, sans-serif";',
    '  ctx.fillText((score >= best && score > 0 ? "NEW BEST! " : "BEST " + best + "  ") + "\\u00b7  PRESS R OR TAP", W / 2, H / 2 + 44);',
    '  ctx.textAlign = "left";',
    '}',
    '',
    '// ---------- game ----------',
    'function reset() {',
    '  score = 0; lives = 3; t = 0; px = W / 2;',
    '  items = []; parts = []; spawnT = 0.5;',
    '  state = "play";',
    '}',
    'function update(dt) {',
    '  t += dt;',
    '  // move the player',
    '  var sp = 340;',
    '  if (keys.arrowleft || keys.a) px -= sp * dt;',
    '  if (keys.arrowright || keys.d) px += sp * dt;',
    '  if (ptr.down) px += Math.max(-sp * dt * 1.7, Math.min(sp * dt * 1.7, ptr.x - px));',
    '  px = Math.max(24, Math.min(W - 24, px));',
    '',
    '  // spawn stars (good) and shards (bad)',
    '  spawnT -= dt;',
    '  if (spawnT <= 0) {',
    '    spawnT = Math.max(0.28, 0.75 - t * 0.008);',
    '    items.push({ x: 20 + Math.random() * (W - 40), y: -20,',
    '                 v: 140 + Math.random() * 120 + t * 3,',
    '                 good: Math.random() < 0.72, r: Math.random() * 6 });',
    '  }',
    '  // move + collide',
    '  for (var i = items.length - 1; i >= 0; i--) {',
    '    var it = items[i];',
    '    it.y += it.v * dt;',
    '    if (it.y > 396 && it.y < 428 && Math.abs(it.x - px) < 58) {',
    '      items.splice(i, 1);',
    '      if (it.good) {',
    '        score += 10;',
    '        burst(it.x, it.y, C.star, 10); beep(880, 0.07, "triangle", 0.05);',
    '      } else {',
    '        lives--; shake = 10; flash = 0.5;',
    '        burst(it.x, it.y, C.shard, 16); beep(140, 0.15, "sawtooth", 0.06);',
    '      }',
    '    } else if (it.y > H + 20) items.splice(i, 1);',
    '  }',
    '  if (lives <= 0) {',
    '    state = "over";',
    '    if (score > best) { best = score; try { localStorage.setItem("starfall_best", best); } catch (e) {} }',
    '  }',
    '  // particles',
    '  for (var j = parts.length - 1; j >= 0; j--) {',
    '    var p = parts[j];',
    '    p.t -= dt;',
    '    if (p.t <= 0) { parts.splice(j, 1); continue; }',
    '    p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 240 * dt;',
    '  }',
    '  shake = Math.max(0, shake - dt * 26);',
    '  flash = Math.max(0, flash - dt * 3);',
    '}',
    'function draw() {',
    '  // background',
    '  var g = ctx.createLinearGradient(0, 0, 0, H);',
    '  g.addColorStop(0, C.bg1); g.addColorStop(1, C.bg2);',
    '  ctx.fillStyle = g; ctx.fillRect(0, 0, W, H);',
    '  // items',
    '  for (var i = 0; i < items.length; i++) {',
    '    var it = items[i];',
    '    ctx.save(); ctx.translate(it.x, it.y); ctx.rotate(it.r + t);',
    '    ctx.fillStyle = it.good ? C.star : C.shard;',
    '    if (it.good) {',
    '      ctx.beginPath();',
    '      for (var k = 0; k < 5; k++) {',
    '        var a1 = -Math.PI / 2 + k * 1.2566, a2 = a1 + 0.6283;',
    '        ctx.lineTo(Math.cos(a1) * 11, Math.sin(a1) * 11);',
    '        ctx.lineTo(Math.cos(a2) * 5, Math.sin(a2) * 5);',
    '      }',
    '      ctx.closePath(); ctx.fill();',
    '    } else {',
    '      ctx.beginPath();',
    '      ctx.moveTo(0, -13); ctx.lineTo(9, 10); ctx.lineTo(-9, 10);',
    '      ctx.closePath(); ctx.fill();',
    '    }',
    '    ctx.restore();',
    '  }',
    '  // player',
    '  ctx.fillStyle = C.player;',
    '  ctx.beginPath(); ctx.arc(px, 412, 16, 0, 6.283); ctx.fill();',
    '  ctx.fillStyle = C.accent;',
    '  ctx.beginPath(); ctx.arc(px, 412, 8, 0, 6.283); ctx.fill();',
    '  // particles',
    '  for (var j = 0; j < parts.length; j++) {',
    '    var p = parts[j];',
    '    ctx.globalAlpha = Math.min(1, p.t * 2.2);',
    '    ctx.fillStyle = p.c;',
    '    ctx.fillRect(p.x - p.s / 2, p.y - p.s / 2, p.s, p.s);',
    '  }',
    '  ctx.globalAlpha = 1;',
    '  // hud',
    '  ctx.fillStyle = C.font; ctx.font = "700 22px system-ui, sans-serif";',
    '  ctx.textAlign = "left";',
    '  ctx.fillText(String(score), 18, 30);',
    '  ctx.textAlign = "right";',
    '  ctx.font = "600 13px system-ui, sans-serif"; ctx.globalAlpha = 0.75;',
    '  ctx.fillText("BEST " + best, W - 18, 28);',
    '  ctx.textAlign = "left";',
    '  for (var h = 0; h < lives; h++) {',
    '    ctx.fillStyle = C.star;',
    '    ctx.beginPath(); ctx.arc(W - 24 - h * 24, H - 24, 8, 0, 6.283); ctx.fill();',
    '  }',
    '  ctx.globalAlpha = 1;',
    '}',
    '',
    '// ---------- input ----------',
    'document.addEventListener("keydown", function (e) {',
    '  if (["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].indexOf(e.key) >= 0) e.preventDefault();',
    '  keys[e.key.toLowerCase()] = true;',
    '  if (state === "title" && (e.key === " " || e.key === "Enter")) reset();',
    '  else if (state === "over" && (e.key.toLowerCase() === "r" || e.key === " " || e.key === "Enter")) reset();',
    '  else if (e.key.toLowerCase() === "m") muted = !muted;',
    '});',
    'document.addEventListener("keyup", function (e) { keys[e.key.toLowerCase()] = false; });',
    'cv.addEventListener("pointerdown", function (e) {',
    '  ptr.down = true; ptr.tap = true;',
    '  ptr.x = (e.clientX - cv.getBoundingClientRect().left) / cv.getBoundingClientRect().width * W;',
    '  if (state !== "play") reset();',
    '});',
    'cv.addEventListener("pointermove", function (e) {',
    '  ptr.x = (e.clientX - cv.getBoundingClientRect().left) / cv.getBoundingClientRect().width * W;',
    '});',
    'window.addEventListener("pointerup", function () { ptr.down = false; });',
    '',
    '// ---------- loop ----------',
    'var last = 0;',
    'function loop(ts) {',
    '  requestAnimationFrame(loop);',
    '  var dt = Math.min(0.05, (ts - last) / 1000 || 0); last = ts;',
    '  if (state === "title") t += dt;',
    '  else if (state === "play") update(dt);',
    '  ctx.save();',
    '  if (shake > 0) ctx.translate((Math.random() - 0.5) * shake, (Math.random() - 0.5) * shake);',
    '  if (state === "title") { draw(); drawTitle(); }',
    '  else if (state === "play") draw();',
    '  else { draw(); drawOver(); }',
    '  if (flash > 0) { ctx.fillStyle = "rgba(255,255,255," + flash + ")"; ctx.fillRect(0, 0, W, H); }',
    '  ctx.restore();',
    '  ptr.tap = false;',
    '}',
    'requestAnimationFrame(loop);',
    '',
    '/* ---------- studio bridge (screenshots for the store) ---------- */',
    'function grab() {',
    '  try { return cv.toDataURL("image/jpeg", 0.9); } catch (e) { return null; }',
    '}',
    'window.tundraShot = function (s) {          // staged screenshots',
    '  var prev = state, data;',
    '  if (s === "title") { state = "title"; draw(); drawTitle(); data = grab(); }',
    '  else if (s === "over") { reset(); score = 4200; lives = 0; state = "over"; draw(); drawOver(); data = grab(); }',
    '  else { reset(); for (var i = 0; i < 25; i++) update(0.05); draw(); data = grab(); }',
    '  state = prev;',
    '  return data;',
    '};',
    'parent.postMessage({ src: "tundra-game", act: "ready" }, "*");',
    'window.addEventListener("message", function (ev) {',
    '  var m = ev.data || {};',
    '  if (m.src !== "tundra-studio") return;',
    '  if (m.act === "ping") parent.postMessage({ src: "tundra-game", act: "pong", ts: m.ts }, "*");',
    '  if (m.act === "shot") parent.postMessage({ src: "tundra-game", act: "shot", ts: m.ts, state: m.state,',
    '    data: window.tundraShot ? window.tundraShot(m.state) : grab() }, "*");',
    '});',
    '<' + '/script>',
    '</body>',
    '</html>'
  ].join('\n');

  /* ---------- Python starter (runs via Pyodide + Tundra API) ---------- */
  var PY_META = '# TUNDRA_META {"title":"Starfall Catch","blurb":"Catch falling stars, dodge the dark shards, and chase your best score.","desc":"Starfall Catch is a tiny arcade game: guide the aurora orb, collect every star, and never touch a shard. Written in Python with the Tundra API — read the code, change the rules, make it yours.","tags":["Arcade","Catch","Cozy","Indie"],"age":"E","price":0,"palette":["#123a55","#8fd8ff"],"hint":"Arrows / A D or drag to move"}';

  var STARFALL_PY = [
    PY_META,
    '# STARFALL CATCH — a Tundra Studio starter game (Python).',
    '# Everything is plain code: read it, change it, break it.',
    '# Hooks: init() on start/restart, update(dt) each frame, draw() each frame.',
    '',
    'px = 400.0            # player x',
    'items = []            # falling stars and shards',
    'spawn_t = 0.0',
    't = 0.0               # seconds survived (drives difficulty)',
    '',
    'def init():',
    '    global px, items, spawn_t, t',
    '    px, items, spawn_t, t = 400.0, [], 0.5, 0.0',
    '    set_lives(3)',
    '    set_score(0)',
    '    set_bg("#123a55", "#071b2c")',
    '    set_title("Starfall Catch", "catch the stars - dodge the shards", "Arrows / A D or drag")',
    '',
    'def update(dt):',
    '    global px, spawn_t, t',
    '    t += dt',
    '    # move the player',
    '    if key("left") or key("a"):',
    '        px -= 340 * dt',
    '    if key("right") or key("d"):',
    '        px += 340 * dt',
    '    if pointer_down():',
    '        step = 340 * dt * 1.7',
    '        dx = pointer_x() - px',
    '        px += max(-step, min(step, dx))',
    '    px = max(24.0, min(776.0, px))',
    '',
    '    # spawn stars (good) and shards (bad)',
    '    spawn_t -= dt',
    '    if spawn_t <= 0:',
    '        spawn_t = max(0.28, 0.75 - t * 0.008)',
    '        items.append({',
    '            "x": rand(20, 780), "y": -20.0,',
    '            "v": rand(140, 260) + t * 3,',
    '            "good": rand(0, 1) < 0.72, "r": rand(0, 6)',
    '        })',
    '',
    '    # move + collide',
    '    for it in items[:]:',
    '        it["y"] += it["v"] * dt',
    '        if 396 < it["y"] < 428 and abs(it["x"] - px) < 58:',
    '            items.remove(it)',
    '            if it["good"]:',
    '                add_score(10)',
    '                burst(it["x"], it["y"], "#ffe27a", 10)',
    '                beep(880, 0.07)',
    '            else:',
    '                set_lives(lives() - 1)',
    '                shake(10)',
    '                flash(0.5)',
    '                burst(it["x"], it["y"], "#8d87a8", 16)',
    '                beep(140, 0.15)',
    '        elif it["y"] > 470:',
    '            items.remove(it)',
    '',
    '    if lives() <= 0:',
    '        game_over()',
    '',
    'def draw():',
    '    for it in items:',
    '        if it["good"]:',
    '            circle(it["x"], it["y"], 11, "#ffe27a")   # a star',
    '        else:',
    '            circle(it["x"], it["y"], 13, "#8d87a8")   # a shard',
    '    # the player orb',
    '    circle(px, 412, 16, "#eaf8ff")',
    '    circle(px, 412, 8, "#8fd8ff")',
    '',
    'def demo(name):',
    '    # pretty scene for store screenshots',
    '    global items',
    '    if name == "play":',
    '        items = [{"x": 250, "y": 120, "v": 0, "good": True, "r": 0},',
    '                 {"x": 430, "y": 190, "v": 0, "good": False, "r": 1},',
    '                 {"x": 580, "y": 90, "v": 0, "good": True, "r": 2}]',
  ].join('\n');

  var EMPTY_PY = [
    '# TUNDRA_META {"title":"My Game","blurb":"A short store blurb (max 160 chars).","desc":"Store description.","tags":["Indie","Arcade"],"age":"E","price":0,"palette":["#1B1F23","#4FB3E8"],"hint":"describe your controls here"}',
    '# My Game — Tundra Studio (Python). Hooks: init(), update(dt), draw().',
    '',
    'def init():',
    '    set_bg("#1B1F23", "#0a0d10")',
    '    set_title("My Game", "", "")',
    '    set_score(0)',
    '',
    'def update(dt):',
    '    pass  # your logic here',
    '',
    'def draw():',
    '    text("My Game", 400, 200, 32, "#F5FAFF", "center")',
  ].join('\n');

  /* ---------- Lua starter (runs via Fengari + Tundra API) ---------- */
  var LUA_META = '-- TUNDRA_META {"title":"Starfall Catch","blurb":"Catch falling stars, dodge the dark shards, and chase your best score.","desc":"Starfall Catch is a tiny arcade game: guide the aurora orb, collect every star, and never touch a shard. Written in Lua with the Tundra API — read the code, change the rules, make it yours.","tags":["Arcade","Catch","Cozy","Indie"],"age":"E","price":0,"palette":["#123a55","#8fd8ff"],"hint":"Arrows / A D or drag to move"}';

  var STARFALL_LUA = [
    LUA_META,
    '-- STARFALL CATCH — a Tundra Studio starter game (Lua).',
    '-- Everything is plain code: read it, change it, break it.',
    '-- Hooks: init() on start/restart, update(dt) each frame, draw() each frame.',
    '',
    'local px, items, spawn_t, t = 400, {}, 0.5, 0',
    '',
    'function init()',
    '  px, items, spawn_t, t = 400, {}, 0.5, 0',
    '  set_lives(3)',
    '  set_score(0)',
    '  set_bg("#123a55", "#071b2c")',
    '  set_title("Starfall Catch", "catch the stars - dodge the shards", "Arrows / A D or drag")',
    'end',
    '',
    'function update(dt)',
    '  t = t + dt',
    '  -- move the player',
    '  if key("left") or key("a") then px = px - 340 * dt end',
    '  if key("right") or key("d") then px = px + 340 * dt end',
    '  if pointer_down() then',
    '    local step = 340 * dt * 1.7',
    '    local dx = pointer_x() - px',
    '    px = px + math.max(-step, math.min(step, dx))',
    '  end',
    '  px = math.max(24, math.min(776, px))',
    '',
    '  -- spawn stars (good) and shards (bad)',
    '  spawn_t = spawn_t - dt',
    '  if spawn_t <= 0 then',
    '    spawn_t = math.max(0.28, 0.75 - t * 0.008)',
    '    table.insert(items, {',
    '      x = rand(20, 780), y = -20,',
    '      v = rand(140, 260) + t * 3,',
    '      good = rand(0, 1) < 0.72, r = rand(0, 6)',
    '    })',
    '  end',
    '',
    '  -- move + collide',
    '  for i = #items, 1, -1 do',
    '    local it = items[i]',
    '    it.y = it.y + it.v * dt',
    '    if it.y > 396 and it.y < 428 and math.abs(it.x - px) < 58 then',
    '      table.remove(items, i)',
    '      if it.good then',
    '        add_score(10)',
    '        burst(it.x, it.y, "#ffe27a", 10)',
    '        beep(880, 0.07)',
    '      else',
    '        set_lives(lives() - 1)',
    '        shake(10)',
    '        flash(0.5)',
    '        burst(it.x, it.y, "#8d87a8", 16)',
    '        beep(140, 0.15)',
    '      end',
    '    elseif it.y > 470 then',
    '      table.remove(items, i)',
    '    end',
    '  end',
    '',
    '  if lives() <= 0 then game_over() end',
    'end',
    '',
    'function draw()',
    '  for _, it in ipairs(items) do',
    '    if it.good then',
    '      circle(it.x, it.y, 11, "#ffe27a")',
    '    else',
    '      circle(it.x, it.y, 13, "#8d87a8")',
    '    end',
    '  end',
    '  circle(px, 412, 16, "#eaf8ff")',
    '  circle(px, 412, 8, "#8fd8ff")',
    'end',
    '',
    'function demo(name)',
    '  if name == "play" then',
    '    items = {',
    '      {x = 250, y = 120, v = 0, good = true, r = 0},',
    '      {x = 430, y = 190, v = 0, good = false, r = 1},',
    '      {x = 580, y = 90, v = 0, good = true, r = 2}',
    '    }',
    '  end',
    'end',
  ].join('\n');

  var EMPTY_LUA = [
    '-- TUNDRA_META {"title":"My Game","blurb":"A short store blurb (max 160 chars).","desc":"Store description.","tags":["Indie","Arcade"],"age":"E","price":0,"palette":["#1B1F23","#4FB3E8"],"hint":"describe your controls here"}',
    '-- My Game — Tundra Studio (Lua). Hooks: init(), update(dt), draw().',
    '',
    'function init()',
    '  set_bg("#1B1F23", "#0a0d10")',
    '  set_title("My Game", "", "")',
    '  set_score(0)',
    'end',
    '',
    'function update(dt)',
    '  -- your logic here',
    'end',
    '',
    'function draw()',
    '  text("My Game", 400, 200, 32, "#F5FAFF", "center")',
    'end',
  ].join('\n');

  /* ============ FROST — the hypereasy game language ============ */
  var FROST_META = '# TUNDRA_META {"title":"Starfall Catch","blurb":"Catch falling stars, dodge the dark shards, and chase your best score.","desc":"Starfall Catch is a tiny arcade game: guide the aurora orb, collect every star, and never touch a shard. Written in Frost, the hypereasy game language — one instruction per line. Read it, change the rules, make it yours.","tags":["Arcade","Catch","Cozy","Indie"],"age":"E","price":0,"palette":["#123a55","#8fd8ff"],"hint":"Arrows / A D or drag to move"}';

  var EMPTY_FROST = [
    FROST_META.replace('Starfall Catch','My Game').replace('Catch falling stars, dodge the dark shards, and chase your best score.','A brand new Frost game — describe it in one line.').replace(/"desc":"[^"]*"/, '"desc":"A brand new game written in Frost, the hypereasy game language."'),
    '# MY GAME — written in Frost, the hypereasy game language.',
    '# One instruction per line. Change anything and press Run.',
    '',
    'title My Game',
    'bg #123a55 #071b2c',
    'goal 10',
    'win Nice one!',
    '',
    'player orb circle 26 #8fd8ff at 50% 86%',
    'control orb arrows drag speed 380',
    '',
    'thing star star 14 #ffd166 fall 220 every 0.8 from top',
    'when orb touches star: score 1, remove star, sound pop, burst'
  ].join('\n');

  var STARFALL_FROST = [
    FROST_META,
    '# STARFALL CATCH — a Tundra Studio starter game (Frost).',
    '# One instruction per line. Change anything and press Run.',
    '',
    'title Starfall Catch',
    'bg #123a55 #071b2c',
    'lives 3',
    'goal 25',
    'win You cleared the sky!',
    'lose The shards got you.',
    '',
    'player orb circle 26 #8fd8ff at 50% 86%',
    'control orb arrows wasd drag speed 380',
    '',
    'thing star star 14 #ffd166 fall 220 every 0.75 from top',
    'thing shard square 12 #ff5d8f fall 300 every 1.15 from top drift 45',
    '',
    'when orb touches star: score 1, remove star, sound pop, burst',
    'when orb touches shard: lives -1, remove shard, sound crash, shake 10, flash',
    '',
    'on score 10: speed star 1.25',
    'on score 20: speed shard 1.3'
  ].join('\n');

  window.Templates = {
    arcade: { id: 'arcade', label: 'Starter game', desc: 'Commented canvas game — catch stars, dodge shards', code: ARCADE },
    empty:  { id: 'empty',  label: 'Empty page',   desc: 'Bare HTML skeleton', code: EMPTY },
    /* language-aware access: get(lang, 'starter'|'empty') */
    get: function (lang, kind) {
      var starter = kind !== 'empty';
      if (lang === 'frost') return { code: starter ? STARFALL_FROST : EMPTY_FROST, label: starter ? 'Starter game (Frost)' : 'Empty Frost file' };
      if (lang === 'py') return { code: starter ? STARFALL_PY : EMPTY_PY, label: starter ? 'Starter game (Python)' : 'Empty Python file' };
      if (lang === 'lua') return { code: starter ? STARFALL_LUA : EMPTY_LUA, label: starter ? 'Starter game (Lua)' : 'Empty Lua file' };
      return { code: starter ? ARCADE : EMPTY, label: starter ? 'Starter game' : 'Empty page' };
    }
  };
})();
